# Generated by Django 3.2.5 on 2021-10-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchEngine', '0002_auto_20210915_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
